model_name: "smooth_diff_unet"  # "diff_unet"
image_size: 96
spatial_size: 96
num_classes: 16
device: "cuda:0"
model_path: null  # "logs/amos/weights/epoch_800.pt"
max_epochs: 2000
val_freq: 20000
batch_size: 10
num_workers: 2
num_gpus: 5
project_name: "diff-unet"
wandb_name: "smoothing-encoder-ver2"
log_dir: "smoothing-encoder-ver2"
loss_combine: "plus"
pretrained: true
use_wandb: true  # false
use_amp: true  # true
use_cache: true  # true

