model_name: smooth_diff_unet
data_name: msd
image_size: 96
spatial_size: 96
classes: cfg/msd/classes.yaml
device: cuda:0
model_path: null # logs/amos/weights/epoch_600.pt
max_epochs: 5000
val_freq: 20000
save_freq: 25
batch_size: 10
num_workers: 2
num_gpus: 5
project_name: smoothing-encoder
wandb_name: null
log_dir: smooth-diff-unet # "diff-unet-msd"
losses: mse,bce,dice # e.g mse,dice,cse,boundary
loss_combine: plus
pretrained: true
use_wandb: false  # false
use_amp: false  # true
use_cache: false  # true

