model_name: diff_unet # swin_unetr # diff_unet # smooth_diff_unet # attention_unet
data_name: btcv # "msd"
data_path: /home/song99/ws/datasets/BTCV
image_size: 96
spatial_size: 96
lr: 2e-4
weight_decay: 1e-3
scheduler: true
warmup_epochs: 100
timesteps: 1000
classes: cfg/btcv/classes.yaml
device: cuda:4
model_path: null # logs/swin-unetr-amos/weights/epoch_3500.pt # resume 
pretrained_path: pretrained/basic_unet/encoder.pt # pretrained/swin_unetr/model_swinvit.pt
max_epochs: 3000
val_freq: 25
save_freq: 250
batch_size: 1
num_workers: 2
device_ids: null
project_name: diff-unet-main
wandb_name: null
log_dir: diff-unet-btcv-14
losses: dice # e.g ce,mse,bce,dice,boundary,dice_ce,dice_focal,generalized_dice,multi_neighbor,hausdorff_er
loss_combine: sum # sum / mean / log
include_background: false
use_wandb: true  # false
use_amp: true  # true
use_cache: false  # true