model_name: swin_unetr # diff_unet  # "smooth_diff_unet"
data_name: amos # "msd"
image_size: 96
spatial_size: 96
classes: cfg/amos/classes.yaml
device: cuda:0
model_path: null # logs/swin-unetr-amos/weights/epoch_1180.pt # resume 
pretrained_path: pretrained/swin_unetr/model_swinvit.pt
max_epochs: 30000
val_freq: 2000000
save_freq: 500
batch_size: 15
num_workers: 2
num_gpus: 5
project_name: swin-unetr
wandb_name: null
log_dir: swin-unetr-amos # "diff-unet-msd"
losses: mse,cse,dice # mse,cse,dice # e.g ce,mse,dice,cse,boundary,dice_ce,dice_focal,generalized_dice
loss_combine: mean # sum / mean / log
remove_bg: true
use_wandb: true  # false
use_amp: true  # true
use_cache: true  # true
