model_name: diff_unet  # "diff_unet"
data_name: msd # "msd"
image_size: 224
spatial_size: 96
classes: cfg/msd/classes.yaml
device: cuda:0
model_path: null # logs/diff-unet-msd-ssl-no-bg-dice/weights/epoch_300.pt
pretrained_path: null # pretrained/basic_unet/encoder.pt
max_epochs: 5000
val_freq: 20000
save_freq: 25
batch_size: 5
num_workers: 2
num_gpus: 5
project_name: diff-unet
wandb_name: null
log_dir: test # "diff-unet-msd"
losses: boundary # mse,cse,dice # e.g ce,mse,dice,cse,boundary,focal
loss_combine: plus
remove_bg: true
use_wandb: false  # false
use_amp: true  # true
use_cache: false  # true
