model_name: diff_unet  # "diff_unet"
data_name: msd # "msd"
image_size: 96
spatial_size: 96
classes: cfg/msd/classes.yaml
device: cuda:0
model_path: null # logs/diff-unet-msd-ssl-no-bg-dice/weights/epoch_300.pt
pretrained_path: null # pretrained/basic_unet/encoder.pt
max_epochs: 5000
val_freq: 20000
save_freq: 25
batch_size: 10
num_workers: 2
num_gpus: 5
project_name: diff-unet
wandb_name: null
log_dir: test # "diff-unet-msd"
losses: cse,boundary,dice # mse,cse,dice # e.g ce,mse,dice,cse,boundary,dice_ce,dice_focal,generalized_dice
loss_combine: mean # sum / mean
remove_bg: true
use_wandb: false  # false
use_amp: true  # true
use_cache: false  # true
