model_name: diff_unet # swin_unetr / diff_unet / smooth_diff_unet / attention_unet / attention_diff_unet
data_name: msd # "msd"
data_path: /home/song99/ws/datasets/MSD
image_size: 96
spatial_size: 96
lr: 2e-4
weight_decay: 1e-4
scheduler: true
warmup_epochs: 100
timesteps: 1000
classes: cfg/msd/classes.yaml
device: cuda:0
model_path: logs/diff-unet-msd-1/weights/epoch_700.pt # resume 
pretrained_path: pretrained/basic_unet/encoder.pt # pretrained/swin_unetr/model_swinvit.pt
max_epochs: 5000
val_freq: 250
save_freq: 100
batch_size: 10
sw_batch_size: 2
overlap: 0.25
num_workers: 2
device_ids: 0,1,2,3,4
project_name: diff-unet-main
wandb_name: null
log_dir: diff-unet-msd-1
losses: mse,bce,dice,focal # ,multi_neighbor # e.g ce,mse,bce,dice,focal,boundary,dice_ce,dice_focal,generalized_dice,multi_neighbor,hausdorff_er,generalized_wasserstein_dice
loss_combine: sum # sum / mean / log
include_background: false
use_wandb: true  # false
use_amp: false  # true
use_cache: false  # true